import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import Providers from './providers';
import { UserProvider } from "./context/UserContext";
import { ToastContainer } from "react-toastify";
import { Session } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: Session;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
          <Providers><UserProvider>
            <Header />
            <main className="pt-4">{children}</main>
            <ToastContainer position="top-right" autoClose={3000} />
            <Footer />
          </UserProvider></Providers>
      </body>
    </html>
  );
}
